
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omblxyyfyctviipzuovf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tYmx4eXlmeWN0dmlpcHp1b3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2ODczMjIsImV4cCI6MjA2MzI2MzMyMn0.5pdH77pIO6Xxxt7IltVxDfwVdunqd7k1zVUijjMzfWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
